version: "3.9"
name: kpi-demo

services:
  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6380:6379"
    networks:
      - backend

  communication-control:
    image: bohdanbulakh/communication-control
    container_name: com-control
    restart: always
    environment:
      Redis__ConnectionString: "redis:6379"
    ports:
      - "8082:8080"
    depends_on:
      - redis
    networks:
      - backend

  map-client:
    image: bohdanbulakh/communication-control-web
    container_name: map-client
    restart: always
    environment:
      VITE_API_BASE_URL: "http://localhost:8082/api/v1/client"
    ports:
      - "8081:80"
    volumes:
      - ./config.json:/usr/share/nginx/html/config.json:ro
    depends_on:
      - communication-control
    networks:
      - backend

  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - backend

  promtail:
    image: grafana/promtail:2.9.2
    container_name: promtail
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - backend
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
    networks:
      - backend
    depends_on:
      - loki

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - backend

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - backend

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - backend

networks:
  backend: